### PR TITLE
Folder Restructure + CI/CD Fix

### PR DESCRIPTION
**Pull request by HarishTeens**
### Previous Folder structure

```
/resolvers
  users.js
  stories.js
  ...

/datasources
  users.js
  stories.js
  ...

/schema
  users.js
  stories.js
  ...

/models
  users.js
  stories.js
  ...
```

### Current Folder Structure

```
apollo/
  users/
    user.resolver.js
    user.model.js
    user.resolver.js
    user.schema.js

  stories/
    story.resolver.js
    story.model.js
    story.resolver.js
    story.schema.js

  ...
```

- This folder structure was changed to keep all files related to a particular entity nearby to access.
- The tests were successfully ran and passed which verifies that the folder restructure didn't break the system even a bit ;) .
  
## Test Report
image

### CODE REVIEW

**Comment by HarishTeens** [comment]
@DesignrKnight Please change the [Dockerfile](https://github.com/dscnitrourkela/project-dates/blob/1c39aa1a3f8458eea1e5cf0e3485fff36ebb5b2a/sources/Dockerfile) to support the present structure 🙌 .

**Comment by DesignrKnight** [comment]
Let's do single branch release based docker trigger. Okay?

When system expands and it requires mukti branch flow, we do multi branch.
Works?

**Comment by HarishTeens** [comment]
@DesignrKnight As you say Sir 🦾

**Comment by DesignrKnight** [comment]
Should I update actions also?

**Comment by DesignrKnight** [comment]
Changing the base of PR and merging to test CI CD

**Pull request merged**
