### PR TITLE
setup cloudinary for media management

### PR DESCRIPTION
**Pull request by HarishTeens**
- created an account with elaichi gmail
- initialised cloudinary SDK
- ready to upload media

### CODE REVIEW

**Comment by HarishTeens** [comment]
This fixes #21

**Comment by HarishTeens** [comment]
Nobody would merge, I merge for meself, sad me 😢

**Comment by DesignrKnight** [comment]
Seems like I am too slow for review. PR to merge in one hour, that is fast

**Comment by roshankshaw** [comment]
Ya that was quick @HarishTeens,  It caused conflicts

**Pull request merged**
