### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by DesignrKnight**

### CODE REVIEW

**Comment by HarishTeens** [comment]
Let's take some time to check whether this is something we really need.

**Comment by DesignrKnight** [comment]
Sir, either we convert repo to private or we use all possible tools at disposal to check it's security. 
No risk

image

**Comment by HarishTeens** [comment]
I'm thinking to convert into private, if it's possible.

**Comment by DesignrKnight** [comment]
Making repo private will make the forks unlinked. Just talk to all before doing

**Pull request merged**
